/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IUiwAdobe: typeof import('~icons/uiw/adobe')['default']
    IUiwAndroidO: typeof import('~icons/uiw/android-o')['default']
  }
}
